### ISSUE TITLE
Veakontroll

### ISSUE THREAD

**Issue by mihkelkalakala** [aleksuibo/is-13#1]
Puudub teatud kohtades veakontroll. Varem oli see olemas, aga eemaldati, nagu näha. Kas see jäi jalgu?

**Comment by aleksuibo** [comment]
Kuna sellel hetkel puudusid aktiivsed veateated, pidasin õigeks see rida eemaldada. Praegusel hetkel sellele mõeldes arvan, et Teil on õigus. Lisasin tagasi veateate kontrolli koodi algusesse.
