### ISSUE TITLE
OST-MÜÜK

### ISSUE THREAD

**Issue by mihkelkalakala** [aleksuibo/is-13#2]
Pole just kõige õigem, et sa järsku ostad asja, mida alguses müüd.

**Comment by aleksuibo** [comment]
Selle asemel et uut kirjet luua on lihtsam vana muuta. Olukorras, kui tegemist on toote vahendamisega on lihtsam peale toote edukat ostu, kirjes muuta ost>müügiks ja tegevust jätkata ??

**Comment by mihkelkalakala** [comment]
Võimalik tõesti.
